//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionPlanner.GCSViews.PrintableReport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntitiesOfPreFlightSchedule : DbContext
    {
        public EntitiesOfPreFlightSchedule()
            : base("name=EntitiesOfPreFlightSchedule")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Report_preflightfchedule_Result> Report_preflightfchedule(string farmId, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateto)
        {
            var farmIdParameter = farmId != null ?
                new ObjectParameter("farmId", farmId) :
                new ObjectParameter("farmId", typeof(string));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("dateFrom", dateFrom) :
                new ObjectParameter("dateFrom", typeof(System.DateTime));
    
            var datetoParameter = dateto.HasValue ?
                new ObjectParameter("dateto", dateto) :
                new ObjectParameter("dateto", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_preflightfchedule_Result>("Report_preflightfchedule", farmIdParameter, dateFromParameter, datetoParameter);
        }
    }
}
